[project]
name = "dynamics-api-desktop-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "msal>=1.32.3",
    "pyqt5>=5.15.11",
]

[tool.uv]
constraint-dependencies = ["pyqt5-qt5 <=5.15.2"]
