[project]
name = "dynamics-api-desktop-app"
version = "0.1.0"
description = "Microsoft Dynamics APIと連携するPython製デスクトップアプリケーション"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "msal>=1.32.3",
    "ttkbootstrap>=1.13.2",
]

[project.scripts]
dynamics-api-app = "src.main:main"
